// generated by build_page.ps1 - do not edit by hand
#pragma once
const char PAGE[] PROGMEM = R"PCHTML(
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>PocketChord</title>
<style>
  :root{
    --bg:#0f1114; --shell:#22262d; --shell2:#1a1e24; --edge:#333944; --ink:#e6e9ef;
    --dim:#79818f; --oled:#05070a; --oledink:#dceaff; --oleddim:#4a6a8f;
    --grey:#8d95a3; --yellow:#f0c04a; --red:#e0574f; --hot:#ff9f45;
  }
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--ink);
       font-family:ui-monospace,Consolas,monospace;display:flex;flex-direction:column;
       align-items:center;gap:14px;padding:20px 10px 40px}

  /* ============ the device ============ */
  #dev{width:720px;max-width:100%;background:linear-gradient(#262b33,#1b1f25);
       border:1px solid var(--edge);border-radius:34px;padding:20px 24px 26px;
       box-shadow:0 20px 50px #000a, inset 0 1px 0 #ffffff10}
  #dev.off{opacity:.5}

  #topbar{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}
  #menus{display:flex;gap:14px}
  .menub{width:34px;height:34px;border-radius:50%;cursor:pointer;user-select:none;
         border:1px solid #00000060;box-shadow:inset 0 -2px 4px #0006, 0 1px 2px #0008;
         display:flex;align-items:center;justify-content:center;font-size:8px;color:#00000090}
  .menub.grey{background:var(--grey)} .menub.yellow{background:var(--yellow)}
  .menub.red{background:var(--red)}
  .menub.held{transform:translateY(2px);box-shadow:inset 0 2px 6px #0009;filter:brightness(1.3)}

  #pwr{display:flex;align-items:center;gap:8px;cursor:pointer;user-select:none}
  #pwr .tk{width:44px;height:21px;border-radius:11px;background:#12151a;
           border:1px solid var(--edge);position:relative}
  #pwr .kn{width:15px;height:15px;border-radius:50%;background:#4a525f;position:absolute;
           top:2px;left:3px;transition:all .12s}
  #pwr.on .tk{background:#173a2a;border-color:#2f7f5c}
  #pwr.on .kn{left:24px;background:#7dffb2;box-shadow:0 0 8px #7dffb2}
  #pwr b{font-size:9px;letter-spacing:2px;color:var(--dim);font-weight:400}
  #pwr.on b{color:#7dffb2}

  /* ============ oled ============ */
  #oled{background:var(--oled);border:1px solid #10161f;border-radius:8px;
        padding:12px 16px;min-height:132px;color:var(--oledink);font-size:12px;
        line-height:1.55;box-shadow:inset 0 0 26px #0af1, inset 0 0 3px #000}
  #dev.off #oled{color:#141a22}
  #dev.off #oled *{color:#141a22 !important}
  .o-top{display:flex;justify-content:space-between;color:var(--oleddim);font-size:11px}
  .o-big{font-size:34px;letter-spacing:1px;margin:4px 0 2px;line-height:1.1}
  .o-sub{color:var(--oleddim);font-size:11px}
  .o-hint{color:var(--oleddim);font-size:10.5px;line-height:1.7;margin-top:4px}
  .o-hint b{color:var(--oledink);font-weight:400}
  #steps{display:flex;gap:2px;margin-top:9px}
  #steps i{flex:1;height:4px;background:#12202e;border-radius:2px}
  #steps i.bar{background:#1d3348}
  #steps i.now{background:var(--oledink)}
  .o-trks{display:flex;gap:5px;margin-top:7px}
  .o-trks span{flex:1;text-align:center;font-size:9px;padding:2px 0;border-radius:3px;
               border:1px solid #1d3348;color:var(--oleddim)}
  .o-trks span.play{border-color:var(--oledink);color:var(--oledink)}
  .o-trks span.rec{background:var(--red);border-color:var(--red);color:#12141a}
  .o-trks span.armed{border-color:var(--red);color:var(--red)}

  /* ============ controls ============ */
  #lower{display:flex;align-items:center;gap:26px;margin-top:22px;flex-wrap:wrap;
         justify-content:center}
  #stickWrap{flex:0 0 150px}
  #stick{width:150px;height:150px;border-radius:50%;position:relative;margin:0 auto;
         background:radial-gradient(circle at 50% 35%,#20242b,#121519);
         border:1px solid #0d1014;box-shadow:inset 0 2px 8px #0009}
  #dot{width:62px;height:62px;border-radius:50%;position:absolute;left:44px;top:44px;
       background:radial-gradient(circle at 45% 35%,#4b535f,#272c34);
       border:1px solid #0e1115;transition:transform .06s;box-shadow:0 3px 6px #0007}
  #stick .lbl{position:absolute;font-size:8.5px;color:#5c6472;white-space:nowrap;pointer-events:none}

  #btns{flex:1;min-width:340px;display:flex;gap:11px;justify-content:center;
        align-items:flex-end;padding-top:38px}
  .cbtn{width:56px;height:56px;border-radius:50%;cursor:pointer;user-select:none;
        background:linear-gradient(#3a414c,#252a32);border:1px solid #0f1216;
        box-shadow:0 3px 5px #0007, inset 0 1px 0 #ffffff12;
        display:flex;flex-direction:column;align-items:center;justify-content:center;
        font-size:13px;color:var(--ink);position:relative}
  .cbtn small{font-size:8px;color:var(--dim);position:absolute;top:7px}
  .cbtn span{margin-top:7px}
  .cbtn:nth-child(even){transform:translateY(-34px)}
  .cbtn.on{background:linear-gradient(var(--hot),#d97a26);border-color:#a85c15;color:#12141a}
  .cbtn.on small{color:#12141a90}
  .cbtn:nth-child(even).on{transform:translateY(-32px)}

  /* ============ footer ============ */
  #foot{width:720px;max-width:100%;display:flex;flex-wrap:wrap;gap:8px;align-items:center;
        font-size:11px;color:var(--dim)}
  .chip{background:#1e2229;border:1px solid var(--edge);border-radius:8px;padding:6px 10px;
        font-size:11px;color:var(--dim);cursor:pointer;user-select:none}
  .chip.on{border-color:#7dffb2;color:#7dffb2}
  #help{width:720px;max-width:100%;font-size:11.5px;color:var(--dim);line-height:1.9}
  #help b{color:var(--ink);font-weight:400}
  kbd{background:#1e2229;border:1px solid var(--edge);border-radius:4px;padding:1px 5px;color:var(--ink)}
</style>
</head>
<body>

<div id="dev" class="off">
  <div id="topbar">
    <div id="pwr"><div class="tk"><div class="kn"></div></div><b>POWER</b></div>
    <div id="menus">
      <div class="menub grey"   data-menu="key">KEY</div>
      <div class="menub yellow" data-menu="sound">SND</div>
      <div class="menub red"    data-menu="mode">MOD</div>
    </div>
  </div>

  <div id="oled"></div>

  <div id="lower">
    <div id="stickWrap"><div id="stick"><div id="dot"></div></div></div>
    <div id="btns"></div>
  </div>
</div>

<div id="foot">
  <span class="chip" id="hwBtn">connect hardware&hellip;</span>
  <span class="chip" id="hwState">not connected</span>
  <span id="hwLast" style="font-size:10px"></span>
</div>

<div id="help">
  <b>chords</b> <kbd>1</kbd>&ndash;<kbd>7</kbd> &nbsp;<b>joystick</b> <kbd>&uarr;</kbd><kbd>&darr;</kbd><kbd>&larr;</kbd><kbd>&rarr;</kbd> &nbsp;<b>power</b> <kbd>P</kbd><br>
  <b>menu buttons</b> <kbd>A</kbd> key &nbsp; <kbd>S</kbd> sound &nbsp; <kbd>D</kbd> mode &mdash; tap to cycle, <i>hold</i> for its page
</div>

<script>
/* ============================================================
   1. THEORY
   ============================================================ */
const NOTES  = ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const SCALES = { major:[0,2,4,5,7,9,11], minor:[0,2,3,5,7,8,10] };
const deg = (s,d) => s[((d%7)+7)%7] + 12*Math.floor(d/7);

const MODS = {
  center:{label:'none'},   up:{label:'7th'},        upright:{label:'add9'},
  right:{label:'maj/min'}, downright:{label:'6th'}, down:{label:'sus2'},
  downleft:{label:'sus4'}, left:{label:'slash'},    upleft:{label:'power'}
};

function buildChord(scaleName, degIdx, mod, keyRoot){
  const S=SCALES[scaleName];
  const root=deg(S,degIdx), third=deg(S,degIdx+2), fifth=deg(S,degIdx+4);
  const sixth=deg(S,degIdx+5), seventh=deg(S,degIdx+6);
  const second=deg(S,degIdx+1), fourth=deg(S,degIdx+3), ninth=deg(S,degIdx+8);

  let notes=[root,third,fifth], bass=root-12, t3=third-root, suffix='', slash=null;
  if(mod==='up')             notes=[root,third,fifth,seventh];
  else if(mod==='upright')   notes=[root,third,fifth,ninth];
  else if(mod==='right'){    const f=(t3===3)?third+1:third-1; notes=[root,f,fifth]; t3=f-root; }
  else if(mod==='downright') notes=[root,third,fifth,sixth];
  else if(mod==='down'){     notes=[root,second,fifth]; suffix='sus2'; }
  else if(mod==='downleft'){ notes=[root,fourth,fifth]; suffix='sus4'; }
  else if(mod==='left'){     bass=third-12; slash=third; }
  else if(mod==='upleft'){   notes=[root,fifth]; suffix='5'; }

  const t5=fifth-root, t7=seventh-root;
  const q=(t3===3&&t5===6)?'dim':(t3===3)?'m':(t3===4&&t5===8)?'aug':'';
  let name;
  if(suffix)                 name=suffix;
  else if(mod==='up')        name=(q==='dim')?'m7b5':(t7===11?q+'maj7':q+'7');
  else if(mod==='upright')   name=q+'add9';
  else if(mod==='downright') name=q+'6';
  else                       name=q;

  const nm=n=>NOTES[(((keyRoot+n)%12)+12)%12];
  let label=nm(root)+name;
  if(slash!==null) label+='/'+nm(slash);
  return {notes,bass,label};
}

/* ============================================================
   2. SYNTH
   ============================================================ */
let ac=null, master=null, verb=null, noiseBuf=null;

const INSTRUMENTS=[
  {n:'Warm Pad', wave:'sawtooth',det:9, a:.35, d:.5, s:.75,r:1.2,cut:1100,env:900, wet:.45,sub:.25},
  {n:'E. Piano', wave:'triangle',det:4, a:.005,d:1.1,s:.15,r:.5, cut:2600,env:2200,wet:.28,sub:.35},
  {n:'Organ',    wave:'square',  det:2, a:.01, d:.05,s:1.0,r:.12,cut:1900,env:0,   wet:.18,sub:.30},
  {n:'Pluck',    wave:'sawtooth',det:14,a:.002,d:.35,s:.0, r:.35,cut:3200,env:2800,wet:.35,sub:.20},
  {n:'Glass',    wave:'sine',    det:6, a:.01, d:.9, s:.2, r:.9, cut:4200,env:1500,wet:.55,sub:.15},
  {n:'Bass',     wave:'square',  det:3, a:.005,d:.4, s:.6, r:.25,cut:800, env:600, wet:.10,sub:.45}
];

function initAudio(){
  if(ac) return;
  ac=new (window.AudioContext||window.webkitAudioContext)();
  master=ac.createGain(); master.gain.value=.22;
  const lim=ac.createDynamicsCompressor(); lim.threshold.value=-8; lim.ratio.value=12;
  master.connect(lim); lim.connect(ac.destination);
  verb=ac.createConvolver(); verb.buffer=makeImpulse(2.4,2.6); verb.connect(master);
  const len=ac.sampleRate*2;
  noiseBuf=ac.createBuffer(1,len,ac.sampleRate);
  const nd=noiseBuf.getChannelData(0);
  for(let i=0;i<len;i++) nd[i]=Math.random()*2-1;
}
function makeImpulse(sec,decay){
  const len=Math.floor(ac.sampleRate*sec), buf=ac.createBuffer(2,len,ac.sampleRate);
  for(let c=0;c<2;c++){ const d=buf.getChannelData(c);
    for(let i=0;i<len;i++) d[i]=(Math.random()*2-1)*Math.pow(1-i/len,decay); }
  return buf;
}
const mtof=m=>440*Math.pow(2,(m-69)/12);

function makeNote(midi,I,when,isBass,len,mul){
  const f=ac.createBiquadFilter(); f.type='lowpass'; f.Q.value=1.2;
  f.frequency.setValueAtTime(I.cut+I.env,when);
  f.frequency.exponentialRampToValueAtTime(Math.max(120,I.cut),when+I.a+I.d);
  const g=ac.createGain(), peak=(isBass?I.sub:.16)*(mul||1);
  g.gain.setValueAtTime(0,when);
  g.gain.linearRampToValueAtTime(peak,when+I.a);
  g.gain.linearRampToValueAtTime(peak*Math.max(I.s,.001),when+I.a+I.d);
  const dw=ac.createGain(); dw.gain.value=1-I.wet; dw.connect(master);
  const ww=ac.createGain(); ww.gain.value=I.wet;   ww.connect(verb);
  f.connect(g); g.connect(dw); g.connect(ww);
  const oscs=[], pair=isBass?1:2;
  for(let k=0;k<pair;k++){
    const o=ac.createOscillator();
    o.type=isBass?'triangle':I.wave;
    o.frequency.value=mtof(midi);
    o.detune.value=(k===0?-I.det:I.det);
    o.connect(f); o.start(when); oscs.push(o);
  }
  const v={g,oscs,r:I.r};
  if(len!=null) releaseVoice(v,when+len);
  return v;
}
function releaseVoice(v,when){
  v.g.gain.cancelScheduledValues(when);
  v.g.gain.setValueAtTime(v.g.gain.value,when);
  v.g.gain.linearRampToValueAtTime(0,when+v.r);
  v.oscs.forEach(o=>{ try{o.stop(when+v.r+.05);}catch(e){} });
}

const SRC=['live','t0','t1','t2','t3'];
let voices={}; SRC.forEach(s=>voices[s]=[]);
function releaseSrc(src,when){
  const t=when!=null?when:ac.currentTime;
  voices[src].forEach(v=>releaseVoice(v,t)); voices[src]=[];
}
function playChordOn(src,midis,inst,when,strum){
  releaseSrc(src,when);
  const I=INSTRUMENTS[inst];
  midis.forEach((m,i)=>{
    const isBass=(i===midis.length-1);
    const off = strum && !isBass ? i*0.045 : 0;
    voices[src].push(makeNote(m,I,when+off,isBass,null));
  });
}
function playArpNote(src,midi,inst,when,len){
  releaseSrc(src,when);
  voices[src].push(makeNote(midi,INSTRUMENTS[inst],when,false,len,1.5));
}

/* ---- drums ---- */
const KITS=[
  {n:'Analog', kf:150,kend:48,kdec:.42,sTone:190,sDec:.16,hDec:.045,hHz:8000},
  {n:'Acoustic',kf:120,kend:55,kdec:.28,sTone:230,sDec:.19,hDec:.035,hHz:9500},
  {n:'Lo-Fi',  kf:100,kend:44,kdec:.5, sTone:160,sDec:.24,hDec:.07, hHz:6000}
];
function noise(when,dur,hz,type,gain){
  const s=ac.createBufferSource(); s.buffer=noiseBuf; s.loop=true;
  const f=ac.createBiquadFilter(); f.type=type; f.frequency.value=hz; f.Q.value=1;
  const g=ac.createGain();
  g.gain.setValueAtTime(gain,when);
  g.gain.exponentialRampToValueAtTime(.0001,when+dur);
  s.connect(f); f.connect(g); g.connect(master);
  s.start(when); s.stop(when+dur+.02);
}
function drumHit(type,when){
  const K=KITS[state.kit];
  if(type==='K'){
    const o=ac.createOscillator(), g=ac.createGain();
    o.type='sine';
    o.frequency.setValueAtTime(K.kf,when);
    o.frequency.exponentialRampToValueAtTime(K.kend,when+.09);
    g.gain.setValueAtTime(.9,when); g.gain.exponentialRampToValueAtTime(.0001,when+K.kdec);
    o.connect(g); g.connect(master); o.start(when); o.stop(when+K.kdec+.02);
  }
  if(type==='S'){
    noise(when,K.sDec,1700,'bandpass',.5);
    const o=ac.createOscillator(), g=ac.createGain();
    o.type='triangle'; o.frequency.value=K.sTone;
    g.gain.setValueAtTime(.35,when); g.gain.exponentialRampToValueAtTime(.0001,when+.09);
    o.connect(g); g.connect(master); o.start(when); o.stop(when+.11);
  }
  if(type==='H') noise(when,K.hDec,K.hHz,'highpass',.22);
  if(type==='O') noise(when,K.hDec*5,K.hHz,'highpass',.18);
}
const PATTERNS=[
  {n:'Four Floor',K:'1000100010001000',S:'0000100000001000',H:'0010001000100010',O:'0000000000000000'},
  {n:'Boom Bap',  K:'1000000010010000',S:'0000100000001000',H:'1010101010101010',O:'0000000000000000'},
  {n:'Rock',      K:'1000000010000000',S:'0000100000001000',H:'1010101010101010',O:'0000000000000000'},
  {n:'Trap',      K:'1000001000100000',S:'0000100000001000',H:'1111111111111111',O:'0000000000000000'},
  {n:'Bossa',     K:'1001001000100100',S:'0010010010100100',H:'1010101010101010',O:'0000000000000000'},
  {n:'Half Time', K:'1000000000000000',S:'0000000010000000',H:'1000100010001000',O:'0000000010000000'}
];

/* ============================================================
   3. STATE
   ============================================================ */
const MODES=[
  {n:'Play',        arp:0, strum:false},
  {n:'Strum',       arp:0, strum:true },
  {n:'Arp Up',      arp:1, strum:false},
  {n:'Arp Down',    arp:2, strum:false},
  {n:'Arp Up-Down', arp:3, strum:false},
  {n:'Arp Random',  arp:4, strum:false}
];
const DEFAULTS=()=>({
  key:0, scale:'major', oct:0, inst:0, held:null, stack:[], dirs:new Set(),
  bpm:100, mode:0, arp:0, strum:false, arpRate:2,
  drums:false, pattern:0, kit:0, loopBars:2, recTrack:-1
});
let state=DEFAULTS(), power=false;
let menuHeld=null, menuUsed=false, menuTime=0;

function blankSrc(){ return {on:false,notes:[],bass:0,inst:0,arp:0,strum:false,
                             key:0,oct:0,arpIdx:0}; }
let srcs={}; SRC.forEach(s=>srcs[s]=blankSrc());
function blankTrack(){ return {state:'empty', events:{}}; }
let tracks=[blankTrack(),blankTrack(),blankTrack(),blankTrack()];

/* ============================================================
   4. TRANSPORT
   ============================================================ */
let transportStart=0, nextStep=0, timer=null, uiStep=-1;
const LOOKAHEAD=.12, TICK=25;
const stepDur=()=>60/state.bpm/4;
const stepsPerLoop=()=>state.loopBars*16;

function startTransport(){
  transportStart=ac.currentTime+.06; nextStep=0;
  clearInterval(timer); timer=setInterval(schedule,TICK);
}
function stopTransport(){ clearInterval(timer); timer=null; }
function liveStep(){ return Math.round((ac.currentTime-transportStart)/stepDur()); }

function schedule(){
  const sd=stepDur();
  while(transportStart+nextStep*sd < ac.currentTime+LOOKAHEAD){
    const when=transportStart+nextStep*sd;
    const spl=stepsPerLoop(), pos=((nextStep%spl)+spl)%spl;
    if(pos===0) onLoopTop();
    stepAudio(pos,when,sd);
    nextStep++;
  }
}
function onLoopTop(){
  tracks.forEach((t,i)=>{
    if(t.state==='armed'){ t.state='rec'; t.events={}; state.recTrack=i; }
    else if(t.state==='rec'){ t.state='play'; if(state.recTrack===i) state.recTrack=-1; }
  });
}
function stepAudio(pos,when,sd){
  if(state.drums){
    const P=PATTERNS[state.pattern], p=pos%16;
    ['K','S','H','O'].forEach(k=>{ if(P[k][p]==='1') drumHit(k,when); });
  }
  tracks.forEach((t,i)=>{
    if(t.state!=='play') return;
    const evs=t.events[pos]; if(evs) evs.forEach(e=>fireEvent('t'+i,e,when));
  });
  const every=state.arpRate;
  if(pos%every!==0) return;
  SRC.forEach(src=>{
    const S=srcs[src];
    if(!S.on||!S.arp) return;
    const pool=S.notes.slice().sort((a,b)=>a-b);
    if(!pool.length) return;
    const ext=pool.concat(pool.map(n=>n+12));
    let idx;
    if(S.arp===1) idx=S.arpIdx%ext.length;
    else if(S.arp===2) idx=ext.length-1-(S.arpIdx%ext.length);
    else if(S.arp===3){ const cyc=(ext.length-1)*2||1, p=S.arpIdx%cyc;
                        idx = p<ext.length? p : cyc-p; }
    else idx=Math.floor(Math.random()*ext.length);
    S.arpIdx++;
    playArpNote(src,ext[idx],S.inst,when,sd*every*.9);
  });
}

/* ============================================================
   5. EVENTS
   ============================================================ */
function fireEvent(src,e,when){
  const S=srcs[src];
  if(e.type==='off'){ S.on=false; releaseSrc(src,when); return; }
  const c=buildChord(e.scale,e.deg,e.mod,e.key);
  const midis=c.notes.map(n=>60+e.key+n+12*e.oct);
  Object.assign(S,{on:true,notes:midis.slice(),bass:c.bass,inst:e.inst,
                   arp:e.arp,strum:e.strum,key:e.key,oct:e.oct,arpIdx:0});
  if(e.arp) releaseSrc(src,when);
  else playChordOn(src,midis.concat([60+e.key+c.bass+12*e.oct]),e.inst,when,e.strum);
}
function record(e){
  if(state.recTrack<0) return;
  const spl=stepsPerLoop();
  let pos=((liveStep()%spl)+spl)%spl;
  const t=tracks[state.recTrack];
  if(e.type==='off' && t.events[pos] && t.events[pos].some(x=>x.type==='on')) pos=(pos+1)%spl;
  (t.events[pos]=t.events[pos]||[]).push(e);
}
function currentMod(){
  const d=state.dirs, u=d.has('up'), dn=d.has('down'), l=d.has('left'), r=d.has('right');
  if(u&&l)return'upleft'; if(u&&r)return'upright';
  if(dn&&l)return'downleft'; if(dn&&r)return'downright';
  if(u)return'up'; if(dn)return'down'; if(l)return'left'; if(r)return'right';
  return 'center';
}
// hold as many buttons as you like - the newest one sounds, and letting it go
// falls back to whatever is still held down instead of cutting out
function sound(i){
  state.held=i;
  const e={type:'on',deg:i,mod:currentMod(),scale:state.scale,key:state.key,
           oct:state.oct,inst:state.inst,arp:state.arp,strum:state.strum};
  fireEvent('live',e,ac.currentTime); record(e); draw();
}
function press(i){
  if(!power) return;
  if(menuHeld){ menuChord(i); return; }
  if(state.stack.indexOf(i)<0) state.stack.push(i);
  sound(i);
}
function lift(i){
  if(!power) return;
  const k=state.stack.indexOf(i);
  if(k>=0) state.stack.splice(k,1);
  if(state.held!==i){ draw(); return; }        // wasn't the one sounding
  if(state.stack.length){ sound(state.stack[state.stack.length-1]); return; }
  state.held=null;
  const e={type:'off'};
  fireEvent('live',e,ac.currentTime); record(e); draw();
}
function armNext(){
  const i=tracks.findIndex(t=>t.state==='empty');
  if(i>=0){ tracks.forEach(t=>{ if(t.state==='armed') t.state='empty'; });
            tracks[i].state='armed'; }
}
function applyMode(){ state.arp=MODES[state.mode].arp; state.strum=MODES[state.mode].strum; }

/* ============================================================
   6. THE THREE MENU BUTTONS
   tap = cycle the obvious thing.  hold = that button's page,
   where the 7 chord buttons and the joystick become controls.
   ============================================================ */
function menuTap(m){
  if(m==='key')   state.key=(state.key+1)%12;
  if(m==='sound') state.inst=(state.inst+1)%INSTRUMENTS.length;
  if(m==='mode'){ state.mode=(state.mode+1)%MODES.length; applyMode(); }
  draw();
}
function menuChord(i){                      // chord button pressed while a menu is held
  menuUsed=true;
  if(menuHeld==='key'){                     // jump to the key of that scale degree
    state.key=(((state.key+deg(SCALES[state.scale],i))%12)+12)%12;
  }
  if(menuHeld==='sound' && i<INSTRUMENTS.length) state.inst=i;
  if(menuHeld==='mode'){
    if(i===0) state.drums=!state.drums;
    if(i===1) state.pattern=(state.pattern+1)%PATTERNS.length;
    if(i===2) state.kit=(state.kit+1)%KITS.length;
    if(i===3) armNext();
    if(i===4){ tracks=[blankTrack(),blankTrack(),blankTrack(),blankTrack()];
               SRC.forEach(s=>{ if(s!=='live'){ releaseSrc(s); srcs[s]=blankSrc(); } });
               state.recTrack=-1; }
    if(i===5) setBpm(state.bpm-5);
    if(i===6) setBpm(state.bpm+5);
  }
  draw();
}
function menuStick(dir){                    // joystick nudged while a menu is held
  menuUsed=true;
  if(menuHeld==='key'){
    if(dir==='right') state.key=(state.key+1)%12;
    if(dir==='left')  state.key=(state.key+11)%12;
    if(dir==='up')    state.scale='major';
    if(dir==='down')  state.scale='minor';
  }
  if(menuHeld==='sound'){
    if(dir==='right') state.inst=(state.inst+1)%INSTRUMENTS.length;
    if(dir==='left')  state.inst=(state.inst+INSTRUMENTS.length-1)%INSTRUMENTS.length;
    if(dir==='up')    state.oct=Math.min(2,state.oct+1);
    if(dir==='down')  state.oct=Math.max(-2,state.oct-1);
  }
  if(menuHeld==='mode'){
    if(dir==='right'){ state.mode=(state.mode+1)%MODES.length; applyMode(); }
    if(dir==='left'){  state.mode=(state.mode+MODES.length-1)%MODES.length; applyMode(); }
    if(dir==='up')     state.arpRate=1;
    if(dir==='down')   state.arpRate=2;
  }
  draw();
}
function menuDown(m){
  if(!power) return;
  menuHeld=m; menuUsed=false; menuTime=Date.now();
  document.querySelectorAll('.menub').forEach(b=>b.classList.toggle('held',b.dataset.menu===m));
  draw();
}
function menuUp(m){
  if(menuHeld!==m) return;
  const quick = !menuUsed && Date.now()-menuTime < 400;
  menuHeld=null;
  document.querySelectorAll('.menub').forEach(b=>b.classList.remove('held'));
  if(quick && power) menuTap(m); else draw();
}
function setBpm(v){ state.bpm=Math.max(50,Math.min(200,v)); startTransport(); }

/* ============================================================
   7. POWER
   ============================================================ */
function powerOn(){
  initAudio();
  if(ac.state==='suspended') ac.resume();
  state=DEFAULTS(); SRC.forEach(s=>srcs[s]=blankSrc());
  tracks=[blankTrack(),blankTrack(),blankTrack(),blankTrack()];
  power=true; menuHeld=null; uiStep=-1;
  startTransport();
  document.getElementById('pwr').classList.add('on');
  document.getElementById('dev').classList.remove('off');
  draw();
}
function powerOff(){
  power=false; stopTransport();
  if(ac) SRC.forEach(s=>releaseSrc(s));
  state=DEFAULTS(); SRC.forEach(s=>srcs[s]=blankSrc());
  tracks=[blankTrack(),blankTrack(),blankTrack(),blankTrack()];
  menuHeld=null;
  document.getElementById('pwr').classList.remove('on');
  document.getElementById('dev').classList.add('off');
  document.querySelectorAll('.menub').forEach(b=>b.classList.remove('held'));
  draw();
}

/* ============================================================
   8. DRAWING THE FACE
   ============================================================ */
const cbtns=[], btnHost=document.getElementById('btns');
for(let i=0;i<7;i++){
  const el=document.createElement('div'); el.className='cbtn';
  el.innerHTML='<small>'+(i+1)+'</small><span>&mdash;</span>';
  el.addEventListener('mousedown',()=>press(i));
  el.addEventListener('mouseup',()=>lift(i));
  el.addEventListener('mouseleave',()=>lift(i));
  btnHost.appendChild(el); cbtns.push(el);
}
const stick=document.getElementById('stick');
[['7th',63,6],['add9',111,26],['maj/min',105,70],['6th',111,112],['sus2',57,131],
 ['sus4',8,112],['slash',3,70],['5',18,26]]
 .forEach(L=>{ const s=document.createElement('span'); s.className='lbl';
   s.textContent=L[0]; s.style.left=L[1]+'px'; s.style.top=L[2]+'px'; stick.appendChild(s); });

document.querySelectorAll('.menub').forEach(b=>{
  const m=b.dataset.menu;
  b.addEventListener('mousedown',()=>menuDown(m));
  b.addEventListener('mouseup',()=>menuUp(m));
  b.addEventListener('mouseleave',()=>menuUp(m));
});
document.getElementById('pwr').onclick=()=> power?powerOff():powerOn();

function trackBar(){
  return '<div class="o-trks">'+tracks.map((t,i)=>
    '<span class="'+(t.state==='empty'?'':t.state)+'">'+
    (t.state==='empty'?'&middot;':t.state==='armed'?'wait':t.state==='rec'?'REC':
     t.state==='play'?'LOOP '+(i+1):'mute')+'</span>').join('')+'</div>';
}
function stepBar(){
  let h='<div id="steps">';
  for(let i=0;i<stepsPerLoop();i++) h+='<i class="'+(i%4===0?'bar':'')+'"></i>';
  return h+'</div>';
}

function draw(){
  const oled=document.getElementById('oled');
  const mod=currentMod();

  if(!power){
    oled.innerHTML='<div class="o-top"><span>POCKETCHORD</span><span>off</span></div>'+
                   '<div class="o-big">&mdash;</div>';
  } else if(menuHeld==='key'){
    oled.innerHTML=
      '<div class="o-top"><span>KEY</span><span>hold</span></div>'+
      '<div class="o-big">'+NOTES[state.key]+' '+state.scale+'</div>'+
      '<div class="o-hint"><b>&#9664;&#9654;</b> key &nbsp; <b>&#9650;</b> major &nbsp; <b>&#9660;</b> minor<br>'+
      '<b>1-7</b> modulate to that chord&rsquo;s key</div>';
  } else if(menuHeld==='sound'){
    oled.innerHTML=
      '<div class="o-top"><span>SOUND</span><span>oct '+(state.oct>0?'+':'')+state.oct+'</span></div>'+
      '<div class="o-big">'+INSTRUMENTS[state.inst].n+'</div>'+
      '<div class="o-hint"><b>&#9664;&#9654;</b> sound &nbsp; <b>&#9650;&#9660;</b> octave<br>'+
      '<b>1-6</b> '+INSTRUMENTS.map(i=>i.n).join(' &middot; ')+'</div>';
  } else if(menuHeld==='mode'){
    oled.innerHTML=
      '<div class="o-top"><span>MODE</span><span>'+state.bpm+' bpm</span></div>'+
      '<div class="o-big">'+MODES[state.mode].n+'</div>'+
      '<div class="o-hint"><b>&#9664;&#9654;</b> mode &nbsp; <b>&#9650;&#9660;</b> arp 1/16 or 1/8<br>'+
      '<b>1</b> drums '+(state.drums?'on':'off')+' &nbsp; <b>2</b> '+PATTERNS[state.pattern].n+
      ' &nbsp; <b>3</b> '+KITS[state.kit].n+'<br>'+
      '<b>4</b> record &nbsp; <b>5</b> clear &nbsp; <b>6/7</b> tempo</div>'+trackBar();
  } else {
    const chord = state.held!==null
      ? buildChord(state.scale,state.held,mod,state.key).label : '—';
    oled.innerHTML=
      '<div class="o-top"><span>'+NOTES[state.key]+' '+state.scale+
        (state.oct?'  oct '+(state.oct>0?'+':'')+state.oct:'')+'</span>'+
        '<span>'+state.bpm+' bpm</span></div>'+
      '<div class="o-big">'+chord+'</div>'+
      '<div class="o-sub">'+INSTRUMENTS[state.inst].n+' &nbsp;&middot;&nbsp; '+MODES[state.mode].n+
        ' &nbsp;&middot;&nbsp; '+(state.drums?PATTERNS[state.pattern].n:'no drums')+
        (mod==='center'?'':' &nbsp;&middot;&nbsp; '+MODS[mod].label)+'</div>'+
      trackBar()+stepBar();
    uiStep=-1;
  }

  const d=state.dirs, x=(d.has('right')?1:0)-(d.has('left')?1:0),
                      y=(d.has('down')?1:0)-(d.has('up')?1:0);
  document.getElementById('dot').style.transform='translate('+(x*36)+'px,'+(y*36)+'px)';

  cbtns.forEach((b,i)=>{
    let label='—';
    if(power){
      if(menuHeld==='key')        label=NOTES[(((state.key+deg(SCALES[state.scale],i))%12)+12)%12];
      else if(menuHeld==='sound') label=i<INSTRUMENTS.length?INSTRUMENTS[i].n.slice(0,4):'-';
      else if(menuHeld==='mode')  label=['drm','pat','kit','rec','clr','-5','+5'][i];
      else                        label=buildChord(state.scale,i,mod,state.key).label;
    }
    b.querySelector('span').textContent=label;
    b.classList.toggle('on', state.held===i);
  });
}

function uiLoop(){
  if(power && ac && !menuHeld){
    const els=document.querySelectorAll('#steps i');
    if(els.length){
      const spl=stepsPerLoop(), p=((liveStep()%spl)+spl)%spl;
      if(p!==uiStep){ els.forEach((e,i)=>e.classList.toggle('now',i===p)); uiStep=p; }
    }
  }
  requestAnimationFrame(uiLoop);
}
uiLoop();

/* ============================================================
   9. KEYBOARD
   ============================================================ */
const DIRKEY={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};
const MENUKEY={a:'key', s:'sound', d:'mode'};
addEventListener('keydown',e=>{
  if(e.repeat) return;
  const k=e.key.toLowerCase();
  if(k==='p'){ power?powerOff():powerOn(); return; }
  if(!power) return;
  if(MENUKEY[k]){ menuDown(MENUKEY[k]); return; }
  if(e.key>='1'&&e.key<='7'){ press(+e.key-1); e.preventDefault(); return; }
  if(DIRKEY[e.key]){
    e.preventDefault();
    if(menuHeld){ menuStick(DIRKEY[e.key]); return; }
    state.dirs.add(DIRKEY[e.key]);
    if(state.held!==null) sound(state.held); else draw();
    return;
  }
  if(k==='z') state.oct=Math.max(-2,state.oct-1);
  if(k==='x') state.oct=Math.min(2,state.oct+1);
  if(k===',') setBpm(state.bpm-5);
  if(k==='.') setBpm(state.bpm+5);
  draw();
});
addEventListener('keyup',e=>{
  const k=e.key.toLowerCase();
  if(MENUKEY[k]){ menuUp(MENUKEY[k]); return; }
  if(!power) return;
  if(e.key>='1'&&e.key<='7') lift(+e.key-1);
  if(DIRKEY[e.key] && !menuHeld){
    state.dirs.delete(DIRKEY[e.key]);
    if(state.held!==null) sound(state.held); else draw();
  }
});

/* ============================================================
   10. HARDWARE
     B12 B9 B13 B10 B14 B11 B15 = chords 1-7 (staggered rows)
     B1 = KEY,  B2 = SOUND,  B3 = MODE
   ============================================================ */
const BTNMAP=[];
BTNMAP[12]='c0'; BTNMAP[9] ='c1'; BTNMAP[13]='c2'; BTNMAP[10]='c3';
BTNMAP[14]='c4'; BTNMAP[11]='c5'; BTNMAP[15]='c6';
BTNMAP[1] ='key'; BTNMAP[2]='sound'; BTNMAP[3]='mode';

let sock=null, hwX=0, hwY=0;
const $=id=>document.getElementById(id);
function hwStatus(t,ok){ $('hwState').textContent=t; $('hwState').classList.toggle('on',!!ok); }

function setStick(x,y){
  if(menuHeld){                              // discrete nudges while a menu is held
    if(x>hwX) menuStick('right'); else if(x<hwX && x!==0) menuStick('left');
    if(y>hwY && y!==0) menuStick('down'); else if(y<hwY) menuStick('up');
    hwX=x; hwY=y; return;
  }
  hwX=x; hwY=y;
  state.dirs.clear();
  if(x>0) state.dirs.add('right'); if(x<0) state.dirs.add('left');
  if(y>0) state.dirs.add('down');  if(y<0) state.dirs.add('up');
  if(state.held!==null) sound(state.held); else draw();
}
function hwButton(i,down){
  const a=BTNMAP[i]; if(!a) return;
  if(a.charAt(0)==='c'){ down? press(+a.slice(1)) : lift(+a.slice(1)); return; }
  down? menuDown(a) : menuUp(a);
}
function hwMsg(line){
  line=(line||'').trim(); if(!line) return;
  $('hwLast').textContent=line;
  const c=line.charAt(0);
  if(c==='B')      hwButton(parseInt(line.slice(1,-1),10), line.slice(-1)==='D');
  else if(c==='J'){ const p=line.slice(1).split(','); setStick(+p[0],+p[1]); }
  else if(c==='P')  power?powerOff():powerOn();
}
function hwConnect(host){
  try{ if(sock) sock.close(); }catch(e){}
  hwStatus('connecting...',false);
  try{
    sock=new WebSocket('ws://'+host+':81/');
    sock.onopen   =()=>hwStatus('connected '+host,true);
    sock.onclose  =()=>hwStatus('disconnected',false);
    sock.onerror  =()=>hwStatus('error - check address / wifi',false);
    sock.onmessage=e=>String(e.data).split('\n').forEach(hwMsg);
  }catch(e){ hwStatus('bad address',false); }
}
$('hwBtn').onclick=()=>{
  let last='192.168.4.1';
  try{ last=localStorage.getItem('pcHost')||last; }catch(e){}
  const h=prompt('ESP32 address', last);
  if(h){ try{ localStorage.setItem('pcHost',h); }catch(e){} hwConnect(h); }
};
if(location.protocol!=='file:' && location.hostname) hwConnect(location.hostname);
else hwStatus('not connected',false);

draw();
</script>
</body>
</html>

)PCHTML";

